name: Update Agenda RSS Feed

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "47 1,18 * * *"
    - cron: "47 */3 * * 1-3"
    # - cron: "*/14 * * * *"
  # workflow_dispatch:

jobs:
  update-agenda-rss-feed:
    name: Update Agenda RSS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JS
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Build Project
        run: |
          npm ci
          tsc

      - name: Generate Feed
        run: |
          set -e
          node dist/src/App.js

      - name: Commit and push updated feed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add feeds/*.rss
          git commit -m 'Update Agenda RSS feed'
          git push
